apiVersion: v1
kind: Service
metadata:
  name: {{ include "dclaw-knowledge.name" . }}
  labels:
    app.kubernetes.io/name: {{ include "dclaw-knowledge.name" . }}
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: 3053
      name: frontend
    - port: {{ .Values.backend.service.port }}
      targetPort: 8139
      name: backend
  selector:
    app.kubernetes.io/name: {{ include "dclaw-knowledge.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
